### ISSUE TITLE
Can't compile python liborigin, missing boost/variant.hpp

### ISSUE THREAD

**Issue by PNorvaisas** [Saluev/python-liborigin2#1]
Hi there,

I run into a problem when trying to compile liborigin python module:

python setup.py build_ext --inplace

running build_ext
skipping 'liborigin.cpp' Cython extension (up-to-date)
building 'liborigin' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c liborigin.cpp -o build/temp.linux-x86_64-2.7/liborigin.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
liborigin.cpp:346:29: fatal error: boost/variant.hpp: No such file or directory
 #include "boost/variant.hpp"
                             ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

I have boost package installed and liborigin has been compiled successfully (well, it couldn't find the 'config.h.in', so I have assumed that 'config.h' should have had this name and renamed it accordingly). In the python case it seems that the script doesn't acknowledge the true boost headers location defined by variable BOOST_INCLUDEDIR and expects it to be in the installation directory with liborigin source files - alas dependencies are broken.

Do you have any idea how to fix it?

Thanks!
Povilas

**Comment by admica** [comment]
For CentOS7 / redhat, install boost-devel to get past this problem.
