### ISSUE TITLE
configuration error

### ISSUE THREAD

**Issue by rphlypo** [Saluev/python-liborigin2#2]
I have obtained the following error running `cmake ../` as recommended. I do not know enough of CMake to debug this one,
```bash
-- Boost version: 1.58.0
CMake Error: File /somepath/python-liborigin2/config.h.in does not exist.
CMake Error at CMakeLists.txt:14 (configure_file):
  configure_file Problem configuring file
```
Any hints ?

**Comment by MrMalter** [comment]
Copy the file `config.h` to `config.h.in` - this seems to resolve the issue.

**Comment by rphlypo** [comment]
Seems to resolve the issue indeed, thanks

**Comment by FilipDominec** [comment]
I had the some trouble, and after spending some time with own search, I finally came here to report this bug. Could you please fix it, e.g., by making a copy or a symlink, please?

**Comment by Saluev** [comment]
Done.
(Guys, this is github, creating a pull request takes a minute!)

**Comment by FilipDominec** [comment]
You are right. Thank you!
