### ISSUE TITLE
Building for Python3

### ISSUE THREAD

**Issue by FilipDominec** [Saluev/python-liborigin2#4]
Hi, Tigran, I am very interested in using the liborigin in my new project for quick data file browsing (https://github.com/FilipDominec/plotcommander). Did you try compiling liborigin for Python3?

**Comment by Saluev** [comment]
Hi! Unfortunately, I haven't tried this. However, I guess it must not be way too difficult. You just need to port Pythonic parts of `liborigin.pyx` to Python 3 (like, replace `xrange` with `range` and so on). I'd greatly appreciate a pull request if you manage to do it.

**Comment by FilipDominec** [comment]
So far, I did not succeed porting python-liborigin2 to python3. It compiles fine as a python3 module (see https://github.com/FilipDominec/plotcommander#other-formats), but  as already expected, it cannot be used in python3 without conversion. The command `opj = liborigin.parseOriginFile('test.opj')` fails with:
 ```
/usr/local/lib/python3.5/dist-packages/liborigin.cpython-35m-x86_64-linux-gnu.so in liborigin.parseOriginFile (liborigin.cpp:33665)()
/usr/local/lib/python3.5/dist-packages/liborigin.cpython-35m-x86_64-linux-gnu.so in string.from_py.__pyx_convert_string_from_py_std__in_string (liborigin.cpp:33999)()
TypeError: expected bytes, str found
```

Therefore I tried to run `2to3 liborigin.pyx`, but obviously it can not crunch the cython-specific syntax, failing with 
```
...
root: Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
RefactoringTool: Can't parse liborigin.pyx: ParseError: bad input: type=1, value=u'objects', context=(u' ', (2, 8))
RefactoringTool: No files need to be modified.
RefactoringTool: There was 1 error:
RefactoringTool: Can't parse liborigin.pyx: ParseError: bad input: type=1, value=u'objects', context=(u' ', (2, 8))
```

I admit to have very little experience with cython and 2-to-3 python porting, so I would be very happy if you could give me any tip how to proceed. (Meanwhile, I can get along with the `opj2dat` command and write a parser for its output, although it is by far not the most elegant approach.)

**Comment by FilipDominec** [comment]
I issued a pull request that should enable the Python3 support. It will need some testing, though.
